#!/usr/bin/env perl
#
# capture_version.pl - Capture git version at deployment time
#
# This script is run during deployment to capture the git version
# and write it to LowVanVersionData.pm for use by the annotation tools.
#
# Usage: capture_version.pl [output_file]
#        Default output: LowVanVersionData.pm (in repo root)
#

use strict;
use warnings;
use File::Basename;
use Cwd qw(abs_path);

my $script_dir = dirname(abs_path($0));
my $repo_dir = dirname($script_dir);  # Go up from Other_Scripts/ to repo root

my $output_file = shift // "$repo_dir/LowVanVersionData.pm";

# Get git version from repo directory
my $version = `git -C "$repo_dir" describe --tags --always 2>/dev/null`;
chomp $version if $version;
$version ||= "unknown";

my $module_content = <<"END_MODULE";
package LowVanVersionData;
use strict;
use warnings;

# Auto-generated by Other_Scripts/capture_version.pl at deployment time - do not edit
# This file is loaded by LowVanVersion.pm to provide the actual version
our \$VERSION = "$version";

1;
END_MODULE

open(my $fh, '>', $output_file) or die "Cannot write to $output_file: $!";
print $fh $module_content;
close($fh);

print "Wrote version '$version' to $output_file\n";
